export enum FormDesignerPanelsEnum {
  QUESTION = 'QUESTION',
  SECTION = 'SECTION',
  FORM = 'FORM',
  UNKNOWN = 'UNKNOWN',
}

export enum PanelsViewsEnum {
  FORM_CONFIGURATION = 'FORM_CONFIGURATION',
  QUESTION_CONFIGURATION = 'QUESTION_CONFIGURATION',
  QUESTION_CREATOR = 'QUESTION_CREATOR',
  VARIANT_CONFIGURATION = 'VARIANT_CONFIGURATION',
  VARIANT_CREATOR = 'VARIANT_CREATOR',
  UNKNOWN = 'UNKNOWN',
}
